#!/usr/bin/env python3
"""Scaffold a new document with the right shape for its type.

The anti-drift argument has three layers:

1. ``check_docs.py`` catches a document that is **already** wrong.
2. ``scripts/doc_types.py`` states, per document type, what a correct one looks
   like and which drift trap it falls into.
3. This script makes the correct shape the **path of least resistance**. A
   document created here starts with its status block, its source binding and its
   required sections already in place, so the author is not being asked to
   remember a rule — they are filling in a form that already encodes it.

Layer 3 is the one that changes behaviour. Layers 1 and 2 only tell you off
afterwards.

Usage:
    python scripts/new_doc.py architecture docs/architecture/queue.md \\
        --title "Queue Subsystem" --source "app/queue/ at HEAD"

    python scripts/new_doc.py --list-types
    python scripts/new_doc.py --template reference   # print, do not write
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from doc_types import TEMPLATE_TYPE, TYPES, required_for  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]

#: Where an author should look next, per type. This is the "read before you
#: write" pointer that makes the governance document a gate rather than a shelf.
POINTERS: dict[str, str] = {
    "architecture": "docs/ARCHITECTURE.md and the ADRs that constrain it (docs/adr/)",
    "reference": "docs/databases-of-record: the module you are documenting, plus docs/CONFIG.md",
    "governance": "docs/GOVERNANCE.md and docs/CI-GATE-SOTA.md (the enforcement points)",
    "adr": "docs/adr/ — read ADR-013 and ADR-011 for the current shape",
    "runbook": "docs/N8N-SETUP.md §9 for the troubleshooting tone that works",
    "guide": "docs/N8N-HANDOVER.md for a beginner-facing example",
    "roadmap": "docs/ROADMAP.md and docs/CAPABILITY_TRACKER.md",
    "register": "docs/ACCEPTED_RISKS.md for row format",
    "generated": "the generator script you are naming",
    "changelog": "docs/CHANGELOG.md — append, do not rewrite",
    "index": "docs/README.md (the only index)",
    "policy": "README.md / SECURITY.md for existing commitments",
    "snapshot": "docs/archive/HEALTH_REPORT_2026-07-28.md for banner format",
}

SECTIONS: dict[str, list[str]] = {
    "architecture": [
        "System Overview",
        "Topology",
        "Package Boundaries",
        "Invariants",
        "Related ADRs",
    ],
    "reference": [
        "Overview",
        "Source of Truth",
        "Configuration / Interface",
        "Defaults",
        "Failure Modes",
    ],
    "governance": ["Scope", "Rules", "Enforcement Points", "Exceptions", "Review"],
    "adr": [
        "Context",
        "Decision",
        "Alternatives considered",
        "Consequences",
        "Related",
    ],
    "runbook": ["Prerequisites", "Procedure", "Verification", "Troubleshooting", "Rollback"],
    "guide": ["What this is", "Getting started", "Common tasks", "Honest gaps", "Where to go next"],
    "roadmap": ["Principles", "Next", "Technical Debt Register", "Success Metrics", "Decision Log"],
    "register": ["Purpose", "Rules", "Register"],
    "generated": ["How this is generated", "Contents"],
    "changelog": ["Unreleased"],
    "index": ["Where to start"],
    "policy": ["Scope", "Commitment", "Reporting", "Enforcement"],
    "snapshot": ["Scope of the measurement", "Findings", "What was not measured"],
}

STATUS_LINE = "**Status**: ACTIVE"


def _slug_to_title(path: Path) -> str:
    stem = path.stem.replace("_", " ").replace("-", " ")
    return stem.title()


def headers_for(
    typ_name: str, status: str, title: str, source: str | None, generated_by: str | None
) -> list[str]:
    typ = TYPES[typ_name]
    lines = [f"# {title}", ""]
    # Status and Type are required of every document, in that order, so the
    # header block is machine-readable as well as human-readable.
    lines.append(f"**Status**: {status}")
    lines.append(f"**Type**: {typ_name}")
    lines.append(f"**Last Updated**: {date.today().isoformat()}")

    for field_name in required_for(status, typ):
        if field_name in {"status", "type", "updated"}:
            continue
        if field_name == "source":
            value = source or "TODO: the code this document describes, e.g. `app/x/` at HEAD"
            lines.append(f"**Source**: {value}")
        elif field_name == "reviewed":
            lines.append(f"**Reviewed**: {date.today().isoformat()}")
        elif field_name == "generated_by":
            value = generated_by or "TODO: scripts/<generator>.py"
            lines.append(f"**Generated by**: {value}")
            lines.append("")
            lines.append("> Do not edit this file by hand. Change the generator and regenerate.")
    lines.append("")
    lines.append(f"> Drift trap for this type: {typ.drift_trap}")
    lines.append("")
    lines.append("---")
    return lines


def skeleton(
    typ_name: str,
    rel: str,
    title: str,
    source: str | None,
    generated_by: str | None,
) -> str:
    typ = TYPES[typ_name]
    status = typ.statuses[0]
    lines = headers_for(typ_name, status, title, source, generated_by)
    lines.append("")

    if status in {"SNAPSHOT", "HISTORICAL"}:
        lines += [
            f"> **Snapshot, not current.** Measured {date.today().isoformat()}. "
            "This document is not maintained; see `docs/DOC-GOVERNANCE.md` §2.",
            "",
        ]

    for sec in SECTIONS.get(typ_name, ["Overview"]):
        lines.append(f"## {sec}")
        lines.append("")
        lines.append("<!-- TODO -->")
        lines.append("")

    lines.append("---")
    lines.append("")
    pointer = POINTERS.get(typ_name, "docs/DOC-GOVERNANCE.md")
    lines.append(
        f"**Write this before you start:** read {pointer}. A document that "
        "contradicts the code is a bug — and the checker will treat it as one."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold a document that cannot drift quietly.")
    ap.add_argument("type", nargs="?", help="document type (see --list-types)")
    ap.add_argument("path", nargs="?", help="target path, e.g. docs/architecture/queue.md")
    ap.add_argument("--title", default=None)
    ap.add_argument("--source", default=None, help="the code this document describes")
    ap.add_argument("--generated-by", default=None, help="generator script, for type=generated")
    ap.add_argument("--list-types", action="store_true")
    ap.add_argument("--template", metavar="TYPE", help="print a template to stdout")
    args = ap.parse_args()

    if args.list_types:
        print("Document types (docs/DOC-GOVERNANCE.md §10):\n")
        for name, typ in sorted(TYPES.items()):
            print(f"  {name:<12} {typ.summary}")
        print(f"\n  {TEMPLATE_TYPE:<12} the same shapes, stored under docs/templates/")
        return 0

    if args.template:
        if args.template not in TYPES:
            print(f"unknown type {args.template!r}; try --list-types", file=sys.stderr)
            return 2
        print(skeleton(args.template, f"docs/{args.template}.md", "<Title>", None, None))
        return 0

    if not args.type or not args.path:
        ap.print_help()
        return 2
    if args.type not in TYPES:
        print(f"unknown type {args.type!r}; try --list-types", file=sys.stderr)
        return 2

    target = Path(args.path)
    if not target.is_absolute():
        target = REPO_ROOT / target
    if target.exists():
        print(f"refusing to overwrite: {target}", file=sys.stderr)
        return 1
    if target.suffix != ".md":
        print("target must be a .md file", file=sys.stderr)
        return 2

    rel = str(target.relative_to(REPO_ROOT))
    # A document's type is also derivable from where it lives, so the checker and
    # the scaffolder agree without the author having to reconcile them.
    if args.type == "adr" and not re.match(r"docs/adr/ADR-\d{3}-", rel):
        print(
            "ADRs must live at docs/adr/ADR-NNN-slug.md with the next free number",
            file=sys.stderr,
        )
        return 2

    title = args.title or _slug_to_title(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        skeleton(args.type, rel, title, args.source, args.generated_by), encoding="utf-8"
    )
    print(f"created {rel} (type={args.type})")
    print("  next: fill the TODOs, then run .venv/bin/python scripts/check_docs.py --strict")
    return 0


if __name__ == "__main__":
    sys.exit(main())
